name: dms
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - python=3.7
  - pip
  - pytorch
  - scipy
  - seaborn
  - matplotlib
  - pip:
      - black
      - dms_variants
      - flake8
      - pylint
